import logging
from pathlib import Path

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def save_markdown_to_file(markdown_content: str, output_filepath: str) -> bool:
    """
    Saves the generated Markdown string to the specified file path.
    Creates parent directories if they do not exist.

    Args:
        markdown_content (str): The Markdown string generated by the LLM.
        output_filepath (str): The destination file path.

    Returns:
        bool: True if successful, False otherwise.
    """
    if not markdown_content:
        logging.error("No markdown content provided to save.")
        return False

    target_path = Path(output_filepath)

    try:
        # Ensure the parent directory exists
        target_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Write the content to the file
        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
            
        logging.info(f"Documentation successfully saved to: {target_path.resolve()}")
        return True

    except PermissionError:
        logging.error(f"Permission denied: Cannot write to {target_path.resolve()}")
    except OSError as e:
        logging.error(f"An OS error occurred while writing the file: {e}")
    except Exception as e:
        logging.error(f"An unexpected error occurred while saving: {e}")
        
    return False