def build_documentation_prompt(raw_context_string: str) -> str:
    """
    Constructs the final LLM prompt by injecting the normalized raw data 
    into a strict system prompt template.

    Args:
        raw_context_string (str): The consolidated string containing all files
                                  (generated by the Input Reader module).

    Returns:
        str: The fully assembled prompt ready to be sent to the LLM API.
    """
    
    # The prompt template is heavily structured to enforce formatting and inference rules.
    prompt_template = f"""You are an Expert Technical Writer and Senior API Architect specializing in IoT device documentation. 

Your task is to analyze a messy collection of raw IoT device data (JSON configurations, code snippets, and developer notes) and synthesize it into a beautifully structured, OpenAPI/Swagger-style Markdown documentation file.

### INFERENCE GUIDELINES (CRITICAL):
1. Synthesize and Cross-Reference: You must connect the dots between the different files. For example, if a code snippet defines an endpoint, and a separate text note mentions a rate limit or authentication header for that endpoint, you must combine them in the final documentation.
2. Handling Edge Cases: Document any known bugs, calibration issues, or delays mentioned in the notes (e.g., sensor anomalies, reboot times) clearly under the relevant endpoints.
3. Missing Data: If a specific detail (like a response payload structure) is missing, infer it logically from the code if possible, otherwise state "Not explicitly defined". Do NOT hallucinate entirely new endpoints or parameters.

### REQUIRED MARKDOWN STRUCTURE:
Your output must strictly follow this structure:

# [Device ID] API Documentation
**Firmware Version:** [Version] | **Status:** [Status] | **Protocols:** [List]

## 1. Overview
[A brief synthesized description of the device and its capabilities based on the inputs.]

## 2. Authentication
[Detail any headers, API keys, or security mechanisms required to interact with the device.]

## 3. Endpoints
[For each endpoint found in the context, create a sub-section using the format below]
### `[HTTP METHOD]` `[Endpoint Path]`
* **Description:** [What it does]
* **Rate Limits / Constraints:** [Any limits mentioned]
* **Request Structure:**
  * [Table or list of parameters/headers]
* **Response Structure:**
  * [Table or JSON block of expected outputs]

## 4. Error Codes & Edge Cases
[A unified table or list of potential errors, hardware constraints, and how to handle them (e.g., unauthorized errors, calibration values).]

### OUTPUT CONSTRAINTS:
- DO NOT output any conversational filler (e.g., "Here is the documentation", "Let me know if you need changes", etc.).
- Output ONLY the raw Markdown content.
- Ensure all tables are properly formatted in Markdown.

### RAW DEVICE CONTEXT:
The following block contains the raw files extracted from the device's repository:

{raw_context_string}
"""
    
    return prompt_template

# ==========================================
# Execution block for testing Step 2 in isolation
# ==========================================
if __name__ == "__main__":
    # Simulating the output from Step 1 (input_reader.py)
    mock_raw_context = """
--- BEGIN FILE: device_config.json ---
{
  "deviceId": "ENV-SENSOR-8832",
  "firmware_version": "v2.1.4-beta"
}
--- END FILE: device_config.json ---

--- BEGIN FILE: extra_notes.txt ---
Hey team, remember: The /reboot endpoint needs an "X-API-Key" header.
--- END FILE: extra_notes.txt ---
"""

    print("Building Prompt...\n")
    final_prompt = build_documentation_prompt(mock_raw_context)
    
    print("=== ASSEMBLED PROMPT READY FOR API ===")
    print(final_prompt)